// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GestorTareasAPI.Models;

public partial class GestorTareasDBContext : DbContext
{
    public GestorTareasDBContext(DbContextOptions<GestorTareasDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tasks> Tasks { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tasks>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(300)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("descripcion");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("estado");
            entity.Property(e => e.FechaDeCreacion)
                .HasColumnType("datetime")
                .HasColumnName("fechaDeCreacion");
            entity.Property(e => e.IdUsuario)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("id_usuario");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("titulo");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Tasks_Users");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(300)
                .HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("email");
            entity.Property(e => e.FechaDeCreacion)
                .HasColumnType("date")
                .HasColumnName("fechaDeCreacion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}