// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestorTareasAPI.Models;

public partial class Tasks
{
    public string Id { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string Estado { get; set; }

    public string IdUsuario { get; set; }

    public DateTime FechaDeCreacion { get; set; }

    public virtual Users IdUsuarioNavigation { get; set; }
}