// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestorTareasAPI.Models;

public partial class Users
{
    public string Id { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public DateTime FechaDeCreacion { get; set; }

    public virtual ICollection<Tasks> Tasks { get; set; } = new List<Tasks>();
}